Repository konveyor/tackle-test-generator-core, pull requests merged in 2022-05, with the labels that each got.

#144 Change license from EPL-2.0 to APL-2.0
  LICENSE
  pom.xml
  tackle-test-generator-ui/pom.xml
  tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
  tackle-test-generator-ui/src/org/konveyor/tackletest/ui/util/TackleTestLogger.java
  tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java
  tackle-test-generator-unit/pom.xml
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/classify/ClassifiedError.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/classify/ClassifyErrors.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/AbstractJUnitTestImporter.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/AbstractTestGenerator.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/EvoSuiteJUnitTestImporter.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/EvoSuiteTestGenerator.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/JUnitTestExporter.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/RandoopJUnitTestImporter.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/RandoopTestGenerator.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/SequenceParser.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/TestSequenceInitializer.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/executor/JUnitExecutor.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/executor/SequenceExecutor.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/CTDCoverageComputer.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/ExtenderSummary.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/ExtenderUtil.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/JavaCollectionTypes.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/SequencePool.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/SequenceUtil.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/util/ProcessLauncher.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/CTDModeler.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/CTDTestPlanGenerator.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/JavaMethodModel.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/ModelAttribute.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/ModelJsonConvertor.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/RapidTypeAnalysis.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/TypeAnalysisResults.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/util/Constants.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/util/TackleTestJson.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/util/TackleTestLogger.java
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/util/Utils.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/TestUtils.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/TestgenIntegrationTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/classify/ClassificationTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/BasicBlockSequenceParseTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/DiffAssertionGeneratorTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/EvoSuiteTestGeneratorTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/RandoopTestGeneratorTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/TestSequenceInitializerTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/executor/SequenceExecutorTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/core/extender/TestSequenceExtenderTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/model/CTDModelingTest.java
  tackle-test-generator-unit/test/java/org/konveyor/tackle/testgen/model/RapidTypeAnalysisTest.java
Labels: documentation

#145 Removed "add_state_diff_assertions" option for tkltest-ui
  tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
Labels: fix

#147 Handle parameterized types with only partial wildcard capture types
  tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
Labels: tkltest-unit, fix
